Repository STC12-team/BookSharingProject, pull requests merged in 2018-11, with the labels that each got.

#67 Рабочий деплой
  Procfile
  build.gradle
  src/main/resources/config.properties.example
  src/main/webapp/WEB-INF/database-context.xml
Labels: help wanted, question

#74 #34 Fixed sonar bug with optional
  src/main/java/ru/innopolis/stc12/booksharing/controller/BookHoldersController.java
  src/main/java/ru/innopolis/stc12/booksharing/exceptions/UnexpectedEmptyListException.java
Labels: bug

#121 Просмотр деталей пользователя
  src/main/db/base/2018-11-05-create-user-details-table.xml
  src/main/db/base/2018-11-05-update-users-table-email-column.xml
  src/main/db/base/base_master.xml
  src/main/java/ru/innopolis/stc12/booksharing/controller/AboutController.java
  src/main/java/ru/innopolis/stc12/booksharing/controller/BookEditionsController.java
  src/main/java/ru/innopolis/stc12/booksharing/controller/LoginController.java
  src/main/java/ru/innopolis/stc12/booksharing/controller/ProfileController.java
  src/main/java/ru/innopolis/stc12/booksharing/controller/RegisterController.java
  src/main/java/ru/innopolis/stc12/booksharing/exceptions/ControllerException.java
  src/main/java/ru/innopolis/stc12/booksharing/exceptions/TestException.java
  src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDao.java
  src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDaoImpl.java
  src/main/java/ru/innopolis/stc12/booksharing/model/dao/mapper/UserDetailsMapper.java
  src/main/java/ru/innopolis/stc12/booksharing/model/pojo/UserDetails.java
  src/main/java/ru/innopolis/stc12/booksharing/service/UserService.java
  src/main/webapp/WEB-INF/bookSharing-servlet.xml
  src/main/webapp/WEB-INF/pages/userProfile.jsp
  src/main/webapp/WEB-INF/security-context.xml
  src/main/webapp/WEB-INF/tags/default.tag
  src/main/webapp/WEB-INF/tags/userdetail.tag
  src/test/java/ru/innopolis/stc12/booksharing/controller/AboutControllerTest.java
  src/test/java/ru/innopolis/stc12/booksharing/controller/ProfileControllerTest.java
  src/test/java/ru/innopolis/stc12/booksharing/model/dao/UserDaoImplTest.java
  src/test/java/ru/innopolis/stc12/booksharing/model/dao/mapper/UserDetailsMapperTest.java
  src/test/java/ru/innopolis/stc12/booksharing/service/UserServiceTest.java
Labels: enhancement

#130 Issue #95
  src/main/webapp/WEB-INF/tags/default.tag
Labels: enhancement

#137 Страница About
  src/main/webapp/WEB-INF/pages/about.jsp
  src/main/webapp/WEB-INF/tags/default.tag
Labels: enhancement

#138 Issue #87
  build.gradle
Labels: help wanted

#133 Редактирование профиля пользователя (status ready)
  src/main/db/data/2018-11-09-insert-default-admin-details.xml
  src/main/db/data/2018-11-09-update-default-admin.xml
  src/main/db/data/data_master.xml
  src/main/java/ru/innopolis/stc12/booksharing/controller/ProfileController.java
  src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDao.java
  src/main/java/ru/innopolis/stc12/booksharing/model/dao/UserDaoImpl.java
  src/main/java/ru/innopolis/stc12/booksharing/model/dao/mapper/UserDetailsMapper.java
  src/main/java/ru/innopolis/stc12/booksharing/model/pojo/UserDetails.java
  src/main/java/ru/innopolis/stc12/booksharing/service/UserService.java
  src/main/webapp/WEB-INF/bookSharing-servlet.xml
  src/main/webapp/WEB-INF/pages/userEdit.jsp
  src/main/webapp/WEB-INF/pages/userProfile.jsp
  src/main/webapp/WEB-INF/tags/menu.tag
  src/main/webapp/WEB-INF/tags/userdetail.tag
  src/main/webapp/WEB-INF/tags/userdetailsedit.tag
  src/main/webapp/resources/themeDefault/js/userEdit.js
  src/test/java/ru/innopolis/stc12/booksharing/controller/ProfileControllerTest.java
  src/test/java/ru/innopolis/stc12/booksharing/controller/RegisterControllerTest.java
  src/test/java/ru/innopolis/stc12/booksharing/model/dao/UserDaoImplTest.java
  src/test/java/ru/innopolis/stc12/booksharing/model/dao/mapper/UserDetailsMapperTest.java
  src/test/java/ru/innopolis/stc12/booksharing/service/UserServiceTest.java
Labels: enhancement

#141 Add internationalization
  src/main/java/ru/innopolis/stc12/booksharing/controller/AboutController.java
  src/main/webapp/WEB-INF/bookSharing-servlet.xml
  src/main/webapp/WEB-INF/messages/messages_en.properties
  src/main/webapp/WEB-INF/messages/messages_ru.properties
  src/main/webapp/WEB-INF/pages/about.jsp
  src/test/java/ru/innopolis/stc12/booksharing/controller/AboutControllerTest.java
Labels: enhancement

#157 Looks like add hibernate support
  build.gradle
  src/main/webapp/WEB-INF/database-context.xml
Labels: enhancement
